In [1]:
import torch

print(torch.__version__)
print(torch.version.cuda)
print(torch.cuda.is_available())

2.9.0.dev20250714+cu129
12.9
True


In [2]:
num_gpus = torch.cuda.device_count()
print("当前可用的GPU数量：", num_gpus)
device = torch.device(f"cuda:{0}")
properties = torch.cuda.get_device_properties(device)
print(f"GPU {0} 的详细信息：")
print("名称：", properties.name)
print("显存大小：", properties.total_memory)

当前可用的GPU数量： 1
GPU 0 的详细信息：
名称： NVIDIA GeForce GTX 1650
显存大小： 4294639616


In [7]:
import numpy as np

x = np.arange(12)
print(x)
print(x.shape)
print(x.size)
print(x.reshape(3, 4))
print(np.zeros((2, 3, 4)))
print(np.ones((2, 3, 4)))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
12
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [5]:
np.random.normal(0, 1, size=(3, 4))

array([[-0.75790575,  1.76229839, -0.6782631 ,  0.37951165],
       [-0.88386306,  1.23801494,  0.76018073, -1.62932899],
       [ 0.00990644, -0.20507101, -0.3540128 , -1.275353  ]])

In [6]:
np.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

array([[2, 1, 4, 3],
       [1, 2, 3, 4],
       [4, 3, 2, 1]])

In [7]:
x = np.array([1, 2, 4, 8])
y = np.array([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(array([ 3,  4,  6, 10]),
 array([-1,  0,  2,  6]),
 array([ 2,  4,  8, 16]),
 array([0.5, 1. , 2. , 4. ]),
 array([ 1,  4, 16, 64]))

In [8]:
np.exp(x)

array([2.71828183e+00, 7.38905610e+00, 5.45981500e+01, 2.98095799e+03])

In [9]:
X = np.arange(12).reshape(3, 4)
Y = np.array([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
np.concatenate([X, Y], axis=0), np.concatenate([X, Y], axis=1)


(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 2,  1,  4,  3],
        [ 1,  2,  3,  4],
        [ 4,  3,  2,  1]]),
 array([[ 0,  1,  2,  3,  2,  1,  4,  3],
        [ 4,  5,  6,  7,  1,  2,  3,  4],
        [ 8,  9, 10, 11,  4,  3,  2,  1]]))

In [10]:
X == Y

array([[False,  True, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [11]:
X.sum()

np.int64(66)

In [12]:
a = np.arange(3).reshape(3, 1)
b = np.arange(2).reshape(1, 2)
a, b

(array([[0],
        [1],
        [2]]),
 array([[0, 1]]))

In [13]:
a + b

array([[0, 1],
       [1, 2],
       [2, 3]])

In [14]:
X[-1], X[1:3]

(array([ 8,  9, 10, 11]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]))

In [15]:
before = id(Y)
Y = X + Y
id(Y) == before

False

In [16]:
Z = np.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 2476097040144
id(Z): 2476097040144


In [17]:
type(X)
B = np.array(X)
type(X), type(B) 
"""在进行深度学习任务的时候，一定要注意深度学习框架定义的张量和NumPy张量之间可能存在的转换问题"""

'在进行深度学习任务的时候，一定要注意深度学习框架定义的张量和NumPy张量之间可能存在的转换问题'

In [18]:
"""深度学习存储和操作数据的主要接口是张量（n维数组）。它提供了各种功能，包括基本数学运算、广
播、索引、切片、内存节省和转换其他Python对象。"""
a = np.array([3.5])
a, a.item(), float(a), int(a)

C:\Users\DaiYongle\AppData\Local\Temp\ipykernel_16448\2956111559.py:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  a, a.item(), float(a), int(a)


(array([3.5]), 3.5, 3.5, 3)

In [19]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')
    f.write('NA,Pave,127500\n') # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [20]:
import pandas as pd

data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [21]:
inputs, outputs = data.iloc[:, 0:1], data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean())
"""方法mean()是列取均值的意思，"""
print(inputs)

   NumRooms
0       3.0
1       2.0
2       4.0
3       3.0


In [4]:
import numpy as np
x = np.array(3.0)
y = np.array(2.0)
"""numpy的一些整型、浮点型的数据类型和python原生的区别在于更适合批量计算"""
x + y, x * y, x / y, x ** y

(np.float64(5.0), np.float64(6.0), np.float64(1.5), np.float64(9.0))

In [5]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [6]:
x[3]

np.int64(3)

In [7]:
len(x)

4

In [8]:
"""用张量表示一个向量（一个轴）时，shape访问向量的长度得到的即是张量沿该轴的长度（维数）"""
x.shape

(4,)

In [9]:
A = np.arange(20).reshape(5, 4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [10]:
"""矩阵的转置"""
A.T

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [11]:
B = np.array([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

array([[1, 2, 3],
       [2, 0, 4],
       [3, 4, 5]])

In [12]:
B == B.T

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [13]:
"""向量是标量的升级，矩阵是向量的升级，张量也是矩阵的升级"""
X = np.arange(24).reshape(2, 3, 4)
X

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [14]:
A = np.arange(20).reshape(5, 4)
B = A.copy()
A, A + B

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]]),
 array([[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22],
        [24, 26, 28, 30],
        [32, 34, 36, 38]]))

In [15]:
A * B

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225],
       [256, 289, 324, 361]])

In [16]:
a = 2
X = np.arange(24).reshape(2, 3, 4)
a + X, (a * X).shape

(array([[[ 2,  3,  4,  5],
         [ 6,  7,  8,  9],
         [10, 11, 12, 13]],
 
        [[14, 15, 16, 17],
         [18, 19, 20, 21],
         [22, 23, 24, 25]]]),
 (2, 3, 4))

In [17]:
x = np.arange(4)
x, x.sum()

(array([0, 1, 2, 3]), np.int64(6))

In [18]:
A.shape, A.sum()

((5, 4), np.int64(190))

In [19]:
A_sum_axis0 = A.sum(axis=0)
"""axis就是选择沿着张量的哪一条轴进行求和的意思（有多少个轴，简单来说就可以通过观察多少层嵌套来确认）"""
A_sum_axis0, A_sum_axis0.shape

(array([40, 45, 50, 55]), (4,))

In [20]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

(array([ 6, 22, 38, 54, 70]), (5,))

In [21]:
A.sum(axis=(0, 1))

np.int64(190)

In [22]:
A.mean(), A.sum() / A.size

(np.float64(9.5), np.float64(9.5))

In [23]:
A, A.shape, A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]]),
 (5, 4),
 array([ 8.,  9., 10., 11.]),
 array([ 8.,  9., 10., 11.]))

In [24]:
sum_A = A.sum(axis=1, keepdims=True)
"""keepdims表示是否保持轴数不变"""
sum_A

array([[ 6],
       [22],
       [38],
       [54],
       [70]])

In [25]:
"""按行计算"""
A.cumsum(axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21],
       [24, 28, 32, 36],
       [40, 45, 50, 55]])

In [26]:
A / sum_A

array([[0.        , 0.16666667, 0.33333333, 0.5       ],
       [0.18181818, 0.22727273, 0.27272727, 0.31818182],
       [0.21052632, 0.23684211, 0.26315789, 0.28947368],
       [0.22222222, 0.24074074, 0.25925926, 0.27777778],
       [0.22857143, 0.24285714, 0.25714286, 0.27142857]])

In [27]:
y = np.ones(4)
x, y, np.dot(x, y)
"""和数学中一样，向量的乘积（点乘）是对应相乘再相加"""

'和数学中一样，向量的乘积（点乘）是对应相乘再相加'

In [28]:
np.sum(x * y)

np.float64(6.0)

In [29]:
"""矩阵-向量积的原理和线性代数矩阵的乘法也是一个道理，要求也是一样"""
A.shape, x.shape, np.dot(A, x)

((5, 4), (4,), array([ 14,  38,  62,  86, 110]))

In [30]:
"""矩阵-矩阵乘法也和线性代数的说法一致"""
B = np.ones(shape=(4, 3))
np.dot(A, B)

array([[ 6.,  6.,  6.],
       [22., 22., 22.],
       [38., 38., 38.],
       [54., 54., 54.],
       [70., 70., 70.]])

In [31]:
u = np.array([3, -4])
"""L2范数（更常见）的意思就是数组内部的元素的平方和开根号"""
u, np.linalg.norm(u)

(array([ 3, -4]), np.float64(5.0))

In [32]:
"""L1范数（不太常见）的意思就是内部元素绝对值相加"""
np.abs(u).sum()

np.int64(7)

In [33]:
"""Frobenius范数满足向量范数的所有性质，它就像是矩阵形向量的L2范数"""
np.linalg.norm(np.ones((4, 9)))

np.float64(6.0)

In [39]:
%matplotlib inline
from matplotlib import pyplot as plt
from matplotlib_inline import backend_inline
def f(x):
    return 3 * x ** 2 - 4 * x

def numerical_lim(f, x, h):
    return (f(x + h) - f(x)) / h

h = 0.1
for i in range(5):
    print(f'h={h:.5f}, numerical limit={numerical_lim(f, 1, h):.5f}')
    h *= 0.1


h=0.10000, numerical limit=2.30000
h=0.01000, numerical limit=2.03000
h=0.00100, numerical limit=2.00300
h=0.00010, numerical limit=2.00030
h=0.00001, numerical limit=2.00003


In [40]:
"""使用svg格式在Jupyter中显示绘图"""
def use_svg_display(): 
    backend_inline.set_matplotlib_formats('svg')

"""设置matplotlib的图表大小"""
def set_figsize(figsize=(3.5, 2.5)):
    use_svg_display()
    plt.rcParams['figure.figsize'] = figsize

"""设置matplotlib的轴"""
def set_axes(axes, xlabel, ylabel, xlim, ylim, xscale, yscale, legend):
    axes.set_xlabel(xlabel)
    axes.set_ylabel(ylabel)
    axes.set_xscale(xscale)
    axes.set_yscale(yscale)
    axes.set_xlim(xlim)
    axes.set_ylim(ylim)
    if legend:
        axes.legend(legend)
    axes.grid()

"""绘制数据点"""
def plot(X, Y=None, xlabel=None, ylabel=None, legend=None, xlim=None, ylim=None, xscale='linear', yscale='linear', fmts=('-', 'm--', 'g-.', 'r:'), figsize=(3.5, 2.5), axes=None):
    if legend is None:
        legend = []
    set_figsize(figsize)
    axes = axes if axes else plt.gca()
    # 如果X有一个轴，输出True
    def has_one_axis(X):
        return (hasattr(X, "ndim") and X.ndim == 1 or isinstance(X, list)
    and not hasattr(X[0], "__len__"))
    if has_one_axis(X):
        X = [X]
    if Y is None:
        X, Y = [[]] * len(X), X
    elif has_one_axis(Y):
        Y = [Y]
    if len(X) != len(Y):
        X = X * len(Y)
    axes.cla()
    for x, y, fmt in zip(X, Y, fmts):
        if len(x):
            axes.plot(x, y, fmt)
        else:
            axes.plot(y, fmt)
    set_axes(axes, xlabel, ylabel, xlim, ylim, xscale, yscale, legend)


In [41]:
x = np.arange(0, 3, 0.1)
print(x)
plot(x, [f(x), 2 * x - 3], 'x', 'f(x)', legend=['f(x)', 'Tangent line (x=1)'])

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]
